function f = fn_central_nonu(dist_x_pl, dist_x_min, u)
f = (1./dist_x_pl - 1./(dist_x_pl + dist_x_min)) .* circshift(u,-1)...
    +(1./dist_x_min - 1./(dist_x_pl)) .* u...
    +(1./(dist_x_pl+dist_x_min) - 1./(dist_x_min)) .*circshift(u,1);
end
